apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-ninja-backend
  name: cloud-ninja-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-ninja-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: cloud-ninja-backend
    spec:
      containers:
      - image: ajay185/backend:tagversion
        name: cloud-ninja-backend
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "50Mi"
            cpu: 100m
          limits:
            memory: "2562Mi"
            cpu: 100m
status: {}
