steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/mar-roidtc501/test:v1", "--build-arg=JAR_FILE=target/backend-java-v1.0.0.jar", "."]
images: ["gcr.io/mar-roidtc501/test"]
